id: P009647
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG20856
  title: དྲིན་ཅན་མ་ལོ།
  author: ''
  volumes:
    bbea7883bb9b4653bbeeeaefc226101a:
      image_group_id: I1KG20891
      title: ''
      volume_number: 1
      total_pages: 172
      base_file: v001.txt
