id: P009647
initial_creation_type: ocr
created_at: 31/03/2020
last_modified_at: 2021-12-19 20:42:41.408558
source_metadata:
  id: bdr:W1KG20856
  title: དྲིན་ཅན་མ་ལོ།
  author: ''
  volumes:
    bbea7883bb9b4653bbeeeaefc226101a:
      image_group_id: I1KG20891
      title: ''
      volume_number: 1
      total_pages: 172
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
